{
 "title": "restaurant-service transactions",
 "description": "Flask",
 "tags": [
  "flask",
  "rservice"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total requests per minute [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (increase(flask_http_request_total[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"rsns\"})",
     "legendFormat": "mem - {{instance}}"
    }
   ]
  },
  {
   "title": "Successful requests per second [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[1m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[1m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"rsns\"}[1m]))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Average response time [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\",service=\"menu-service\"}[1m]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\",service=\"menu-service\"}[1m]))",
     "legendFormat": "menu-service"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\",service=\"billing-service\"}[1m]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\",service=\"billing-service\"}[1m]))",
     "legendFormat": "billing-service"
    },
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\",service=\"booking-service\"}[1m]))\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\",service=\"booking-service\"}[1m]))",
     "legendFormat": "booking-service"
    }
   ]
  },
  {
   "title": "Median response time [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"menu-service\",status=\"200\"}[1m])))",
     "legendFormat": "menu-service"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"billing-service\",status=\"200\"}[1m])))",
     "legendFormat": "billing-service"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"booking-service\",status=\"200\"}[1m])))",
     "legendFormat": "booking-service"
    }
   ]
  },
  {
   "title": "process open fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"rsns\"})",
     "legendFormat": "fds"
    }
   ]
  },
  {
   "title": "Requests under 100 ms [5m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (service) (increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.1\"}[5m]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[5m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "90th %ile response time [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"menu-service\",status=\"200\"}[1m])))",
     "legendFormat": "menu-service"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"billing-service\",status=\"200\"}[1m])))",
     "legendFormat": "billing-service"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(flask_http_request_duration_seconds_bucket{service=\"booking-service\",status=\"200\"}[1m])))",
     "legendFormat": "booking-service"
    }
   ]
  }
 ]
}