apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
  - protocol: "TCP"
    port: 30001
    targetPort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  selector:
    matchLabels:
      app: menu-service
  replicas: 4
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
      - name: menu-service
        image: 'ghcr.io/subclassy/menu-service:v1.0'
        imagePullPolicy: Always
        ports:
        - containerPort: 30001