apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
  - protocol: "TCP"
    port: 30003
    targetPort: 30003
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  selector:
    matchLabels:
      app: booking-service
  replicas: 1
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: 'ghcr.io/subclassy/booking-service:v1.0'
        imagePullPolicy: Always
        ports:
        - containerPort: 30003