apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing-service
  ports:
  - protocol: "TCP"
    port: 30002
    targetPort: 30002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
spec:
  selector:
    matchLabels:
      app: billing-service
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
      - name: billing-service
        image: 'ghcr.io/subclassy/billing-service:v1.0'
        imagePullPolicy: Always
        ports:
        - containerPort: 30002